- name: Checking, if ~/.config/alacritty directory exists already on disk
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/alacritty"
  register: alacritty_directory

- name: Create Alacritty directory in ~/.config
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    mode: '0755'
  with_items:
    - "{{ lookup('env', 'HOME') }}/.config/alacritty"
  when: alacritty_directory.stat.exists == False

- name: Remove .alacritty.toml file from ~/ if it exists already
  become: true
  command: rm -f "{{ lookup('env', 'HOME') }}/.alacritty.toml"

- name: Remove .alacritty.toml file from ~/.config/alacritty if it exists already
  become: true
  command: rm -f "{{ lookup('env', 'HOME') }}/.config/alacritty/alacritty.toml"

- name: Link Own Alacritty Configuration File
  become: true
  become_user: "{{ username }}"
  command: ln -s "{{ personal_github_directory }}/dotfiles/alacritty/.alacritty.toml-macos" "{{ lookup('env', 'HOME') }}/.config/alacritty/alacritty.toml"
