- name: Core Utilities - Set 1 - Install apt packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - "build-essential"
    - "cmake"
    - "pkg-config"
    - "libpthread-stubs0-dev"
    - "apt-transport-https"
    - "ca-certificates"
    - "virtualenv"
    - "gpg"
    - "lua5.3"
    - "unzip"
    - "libtool"
    - "libtool-bin"
    - "gettext"
    - "software-properties-common"
    - "gnupg2"
    - "libfreetype6-dev"
    - "libfontconfig1-dev"
    - "libxcb-xfixes0-dev"
    - "libxkbcommon-dev"
    - "curl"
    - "wget"
    - "bat"
    - "htop"
    - "lsof"
    - "ccache"
    - "ninja-build"
    - "graphviz"
    - "ripgrep"
    - "fzf"
    - "ssh"
    - "i3"
    - "tmux"
    - "dconf-editor"
    - "nvidia-settings"
    - "pavucontrol"
    - "moreutils"
    - "snapd"
    - "plantuml"
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 2 - Download, Unzip and install deno
  become: true
  command: sh -c "{{ item }}"
  with_items:
    - "curl -Lo 'deno.zip' 'https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip'"
    - "sudo unzip -d /usr/local/bin deno.zip"
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 3 - Copy Meslo Nerd Font directory to ~/.fonts
  become: true
  become_user: "{{ username }}"
  copy:
    src: "{{ font_source }}"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: '0755'
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 4 - Rebuild font cache
  become: true
  command: fc-cache -fv
  tags:
    - install
    - neovim
    - core
