- name: Ensure ~/.ssh directory exists
  become_user: "{{ username }}"
  file:
    dest: "{{ localhost_ssh_key_destination | dirname }}"
    mode: 0700
    state: directory

- name: Copy private SSH key
  become_user: "{{ username }}"
  copy:
    src: "{{ ssh_key_source }}"
    dest: "{{ localhost_ssh_key_destination }}"
    mode: 0600

- name: Copy public SSH key
  become_user: "{{ username }}"
  copy:
    src: "{{ ssh_key_source }}.pub"
    dest: "{{ localhost_ssh_key_destination }}.pub"
    mode: 0644
