- name: Link Own tmux Configuration File
  become: true
  become_user: "{{ username }}"
  command: ln -s "{{ personal_github_directory }}/dotfiles/tmux/.tmux.conf" "{{ lookup('env', 'HOME') }}/.tmux.conf"