- name: ZSH - Install Oh-My-ZSH
  become: true
  become_user: "{{ username }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: ZSH - Delete Original .zshrc File
  command: rm "{{ lookup('env', 'HOME') }}/.zshrc"

- name: ZSH - Link Own .zshrc File
  become: true
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - ln -s "{{ personal_github_directory }}/dotfiles/zsh/.zshrc-macos" "{{ lookup('env', 'HOME') }}/.zshrc"
    - ln -s "{{ personal_github_directory }}/dotfiles/zsh/.zsh_aliases" "{{ lookup('env', 'HOME') }}/.zsh_aliases"
    - ln -s "{{ personal_github_directory }}/dotfiles/zsh/mannydark.zsh-theme" "{{ lookup('env', 'HOME') }}/.oh-my-zsh/themes/mannydark.zsh-theme"
