---
- name: Install Apple macOS core utilities
  become: true
  vars:
    task_name: "---> Installing core utilities..."
  when: os_type == "macos"
  block:
    - name: "{{ task_name }}"
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - "bat"
        - "composer"
        - "curl"
        - "deno"
        - "docker"
        - "eza"
        - "fzf"
        - "gnupg"
        - "graphviz"
        - "grep"
        - "ifstat"
        - "jq"
        - "mas"
        - "MonitorControl"
        - "neovim"
        - "node-sass"
        - "nvm"
        - "php"
        - "pinentry-mac"
        - "plantuml"
        - "pngpaste"
        - "ripgrep"
        - "sketchybar"
        - "speedtest-cli"
        - "sqlite"
        - "tmate"
        - "tmux"
        - "trash"
        - "tree"
        - "vue-cli"
        - "wget"
        - "yarn"
        - "zsh-autosuggestions"
        - "zsh-syntax-highlighting"
        - "homebrew/cask/aldente"
        - "homebrew/cask/alfred"
        - "homebrew/cask/apparency"
        - "homebrew/cask/bartender"
        - "homebrew/cask/displaylink"
        - "homebrew/cask/font-meslo-lg-nerd-font"
        - "homebrew/cask/font-space-mono-nerd-font"
        - "homebrew/cask/font-hack-nerd-font"
        - "homebrew/cask/istat-menus"
        - "homebrew/cask/karabiner-elements"
        - "homebrew/cask/macpass"
        - "homebrew/cask/qlcolorcode"
        - "homebrew/cask/qlimagesize"
        - "homebrew/cask/qlmarkdown"
        - "homebrew/cask/qlstephen"
        - "homebrew/cask/qlvideo"
        - "homebrew/cask/quicklook-json"
        - "homebrew/cask/quicklookase"
        - "homebrew/cask/raycast"
        - "homebrew/cask/suspicious-package"
        - "homebrew/cask/"
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
        - ""
