---
- name: Install Ubuntu core utilities
  become: true
  vars:
    task_name: "---> Installing core utilities..."
  when: os_type == "ubuntu"
  block:
    - name: "{{ task_name }}"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "build-essential"
        - "cmake"
        - "pkg-config"
        - "libpthread-stubs0-dev"
        - "apt-transport-https"
        - "ca-certificates"
        - "virtualenv"
        - "gpg"
        - "lua5.3"
        - "unzip"
        - "libtool"
        - "libtool-bin"
        - "gettext"
        - "software-properties-common"
        - "gnupg2"
        - "libfreetype6-dev"
        - "libfontconfig1-dev"
        - "libxcb-xfixes0-dev"
        - "libxkbcommon-dev"
        - "curl"
        - "wget"
        - "bat"
        - "htop"
        - "lsof"
        - "ccache"
        - "ninja-build"
        - "graphviz"
        - "ripgrep"
        - "fzf"
        - "ssh"
        - "i3"
        - "dconf-editor"
        - "nvidia-settings"
        - "pavucontrol"
        - "moreutils"
        - "snapd"
        - "plantuml"

    - name: Notify about core utilities installation
      ansible.builtin.debug:
        msg: "Core utilities installation completed."
