---
- name: Install Core Utilities
  become: true
  vars:
    task_name: "---> Installing core utilities..."
  block:
    - name: Install Arch Linux Core Utilities
      when: os_type == "arch"
      with_items:
        - "base-devel"
        - "git"
        - "cmake"
        - "curl"
        - "ninja"
        - "unzip"
      block:
        - name: Install base development tools
          ansible.builtin.package:
            name: "{{ item }}"
            state: present

        - name: Check if yay is installed
          ansible.builtin.command: which yay
          register: yay_check
          ignore_errors: true
          changed_when: false

        - name: Clone yay repository
          git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay
          when: yay_check.rc != 0
          become: false

- when: os_type == "ubuntu"
      name: "{{ task_name }}"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "build-essential"
        - "cmake"
        - "pkg-config"
        - "libpthread-stubs0-dev"
        - "apt-transport-https"
        - "ca-certificates"
        - "virtualenv"
        - "gpg"
        - "lua5.3"
        - "unzip"
        - "libtool"
        - "libtool-bin"
        - "gettext"
        - "software-properties-common"
        - "gnupg2"
        - "libfreetype6-dev"
        - "libfontconfig1-dev"
        - "libxcb-xfixes0-dev"
        - "libxkbcommon-dev"
        - "curl"
        - "wget"
        - "bat"
        - "htop"
        - "lsof"
        - "ccache"
        - "ninja-build"
        - "graphviz"
        - "ripgrep"
        - "fzf"
        - "ssh"
        - "i3"
        - "dconf-editor"
        - "nvidia-settings"
        - "pavucontrol"
        - "moreutils"
        - "snapd"
        - "plantuml"
