- name: Set Up Accessibility
  become: true
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.universalaccess voiceOverEnabled -bool false"
    - "defaults write com.apple.universalaccess reduceMotion -bool true"
    - "defaults write com.apple.universalaccess reduceTransparency -bool true"
    - "killall -u $USER cfprefsd"