---
- name: Set Up Accessibility
  become: true
  become_user: "{{ username }}"
  when: os_type == "macos"
  block:
    - name: Disable VoiceOver
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: voiceOverEnabled
        type: bool
        value: false
        state: present

    - name: Reduce Motion
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: reduceMotion
        type: bool
        value: true
        state: present

    - name: Reduce Transparency
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: reduceTransparency
        type: bool
        value: true
        state: present

    - name: Restart cfprefsd
      ansible.builtin.shell: "killall -u $USER cfprefsd"
      state: present

    - name: Notify about Accessibility setup
      ansible.builtin.debug:
        msg: "Apple macOS Accessibility setup completed."
