---
- name: Set Up AirDrop & Handoff
  become: true
  become_user: "{{ username }}"
  when: os_type == "macos"
  block:
    - name: Disable AirDrop
      community.general.osx_defaults:
        domain: com.apple.NetworkBrowser
        key: BrowseAllInterfaces
        type: bool
        value: false
        state: present

    - name: Notify about AirDrop setup
      ansible.builtin.debug:
        msg: "Apple macOS AirDrop setup completed."
