---
- name: Set Up Appearance
  become: true
  become_user: "{{ username }}"
  when: os_type == "macos"
  block:
    - name: Set Dark Mode
      ansible.general.osx_defaults:
        domain: -g
        key: AppleInterfaceStyle
        type: string
        value: Dark
        state: present

    - name: Set Accent Color
      ansible.general.osx_defaults:
        domain: -g
        key: AppleAccentColor
        type: int
        value: 6
        state: present

    - name: Reduce Desktop Tinting
      ansible.general.osx_defaults:
        domain: -g
        key: AppleReduceDesktopTinting
        type: bool
        value: true
        state: present

    - name: Show Scroll Bars
      ansible.general.osx_defaults:
        domain: -g
        key: AppleShowScrollBars
        type: string
        value: WhenScrolling
        state: present

    - name: Set Scroller Paging Behavior
      ansible.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleScrollerPagingBehavior
        type: bool
        value: true
        state: present

    - name: Notify about Appearance setup
      ansible.builtin.debug:
        msg: "Apple macOS Appearance setup completed."
