---
- name: Set Up Control Centre
  become: true
  become_user: "{{ username }}"
  when: os_type == "macos"
  block:
    - name: Show WiFi in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Wi-Fi"
        value: true
        state: present

    - name: Show Bluetooth in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Bluetooth"
        value: true
        state: present

    - name: Show AirDrop in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible AirDrop"
        value: true
        state: present

    - name: Show Focus in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Focus"
        value: true
        state: present

    - name: Do not show Stage Manager in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible StageManager"
        value: false
        state: present

    - name: Show Screen Mirroring in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible ScreenMirroring"
        value: true
        state: present

    - name: Show Display in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Display"
        value: true
        state: present

    - name: Show Sound in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Sound"
        value: true
        state: present

    - name: Do not show Now Playing in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible NowPlaying"
        value: true
        state: present

    - name: Show Battery in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Battery"
        value: false
        state: present

    - name: Show Keyboard Brightness in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible KeyboardBrightness"
        value: true
        state: present

    - name: Show Time Machine in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible TimeMachine"
        value: true
        state: present

    - name: Autohide Menu Bar
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: _HIHideMenuBar
        value: true
        state: present

    - name: Do not show rescent items in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible RecentItems"
        value: false
        state: present

    - name: Set Recent Documents Limit to 0
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSRecentDocumentsLimit
        value: 0
        state: present

    - name: Do not show Spotlight in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Spotlight"
        value: false
        state: present

    - name: Do not show Siri in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Siri"
        value: false
        state: present

    - name: Do not show Hearing in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Hearing"
        value: false
        state: present

    - name: Do not show Fast User switching in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible FastUserSwitching"
        value: false
        state: present

    - name: Do not show Accessibility in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible Accessibility"
        type: int
        value: 8
        state: present

    - name: Show Music Recognition in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: "NSStatusItem Visible MusicRecognition"
        value: true
        state: present

    - name: Show Date in Control Centre
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        key: ShowDate
        type: int
        value: 18
        state: present

    - name: Restart Control Centre
      ansible.builtin.command: killall ControlCenter
      state: present

    - name: Restart SystemUIServer
      ansible.builtin.command: killall SystemUIServer
      state: present

    - name: Notify about Control Centre setup
      ansible.builtin.debug:
        msg: "Apple macOS Control Centre setup completed."
