- name: Set Up Displays
  become: true
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.spaces spans-displays -bool false"
    - "defaults write com.apple.systempreferences QLDisplayResolutionOn -bool true"
    - "defaults write NSGlobalDomain AppleFontSmoothing -int 2"
    - "killall Dock"
    - "killall cfprefsd"

- name: Change Mode of Displays Script to an Executable
  become_user: "{{ username }}"
  become: true
  command: chmod +x "{{ personal_github_directory }}/ansible/scripts/system-settings/displays.sh"

- name: Run Displays Script
  become: true
  shell: "{{ personal_github_directory }}/ansible/scripts/system-settings/displays.sh"