- name: Set Up Dock
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.dock tilesize -int 30"
    - "defaults write com.apple.dock magnification -bool false"
    - "defaults write com.apple.dock autohide -bool true"
    - "defaults write com.apple.dock launchanim -bool false"
    - "defaults write com.apple.dock show-process-indicators -bool true"
    - "defaults write com.apple.dock show-recents -bool false"
    - "defaults write com.apple.WindowManager GloballyEnabled -bool false"
    - "defaults write com.apple.WindowManager AutoHide -bool true"
    - "defaults write com.apple.WindowManager StandardHideWidgets -int 0"
    - "defaults write com.apple.WindowManager StageManagerHideWidgets -int 0"
    - "defaults write -globalDomain NSCloseAlwaysConfirmsChanges -bool true"
    - "defaults write com.apple.dock mru-spaces -bool false"
    - "defaults write com.apple.dock wvous-tl-corner -int 0"
    - "defaults write com.apple.dock wvous-tr-corner -int 0"
    - "defaults write com.apple.dock wvous-bl-corner -int 0"
    - "defaults write com.apple.dock wvous-br-corner -int 0"
    - "defaults write com.apple.dock persistent-apps -array"
    - "killall Dock"
