---
- name: Set Up Lock Screen
  become: true
  become_user: "{{ username }}"
  when: os_type == "macos"
  block:
    - name: Set screen saver idle time to 0
      community.general.osx_defaults:
        domain: com.apple.screensaver
        key: idleTime
        type: int
        value: 0
        state: present

    - name: Ask for password after screen saver starts
      community.general.osx_defaults:
        domain: com.apple.screensaver
        key: askForPassword
        type: int
        value: 1
        state: present

    - name: Set asking for password delay to 0
      community.general.osx_defaults:
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0
        state: present

    - name: Set VoiceOver OnScreenUIEnabled to false
      community.general.osx_defaults:
        domain: com.apple.VoiceOver
        key: OnScreenUIEnabled
        type: bool
        value: false
        state: present

    - name: Set universalaccess stickyKey to false
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: stickyKey
        type: bool
        value: false
        state: present

    - name: Set universalaccess slowKey to false
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: slowKey
        type: bool
        value: false
        state: present

    - name: Set hibernatemode to 0
      ansible.builtin.command:
        cmd: sudo pmset -a hibernatemode 0
      state: present

    - name: Notify about Lock Screen setup
      ansible.builtin.debug:
        msg: "Apple macOS Lock Screen setup completed."
