---
- name: Copy public SSH key
  become_user: "{{ username }}"
  vars:
    task_name: "---> Copying public SSH key to disk..."
  block:

    - when: os_type in unix_os_types
      name: "{{ task_name }}"
      copy:
        src:  "{{ public_ssh_key_source }}"
        dest: "{{ unix_public_ssh_key_file_path }}"
        mode: 0644

    - when: os_type == "windows"
      name: "{{ task_name }}"
      copy:
        src:  "{{ public_ssh_key_source }}"
        dest: "{{ windows_public_ssh_key_file_path }}"
        mode: 0644
