- name: Install ZSH-Plugins (Ubuntu)
  become: true
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/zsh-users/zsh-autosuggestions.git", dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions" }
    - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-syntax-highlighting" }
  when: os_type in ["ubuntu"]

