---
- name: Create directories
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Creating directories on file system..."
  block:
    - name: "{{ task_name }}"
      when: os_type in ["arch", "macos", "ubuntu"]
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ username }}"
        mode: "0755"
      with_items:
        - "{{ unix_directories }}"

    - name: "{{ task_name }}"
      when: os_type == 'windows'
      ansible.windows.win_file:
      path: "{{ item }}"
      state: directory
      owner: "{{ username }}"
      mode: "0755"
      with_items:
        - "{{ windows_directories }}"

    - name: Notify about creating directories
      ansible.builtin.debug:
        msg: "Creating directories completed."
