---
neovim_github_repository:        'https://github.com/neovim/neovim.git'
unix_neovim_directory:           "{{ unix_home_directory }}/neovim"
unix_nvim_config_directory:      "{{ unix_home_directory }}/.config/nvim"
unix_nvim_dotfiles_directory:    "{{ unix_dotfiles_directory }}/nvim"
windows_neovim_directory:        "{{ windows_wsl_home_directory }}\\neovim"
windows_nvim_config_directory:   "{{ windows_wsl_home_directory }}\\.config\\nvim"
windows_nvim_dotfiles_directory: "{{ windows_dotfiles_directory }}\\nvim"
