- name: Checking, if set-up-dev-machine repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/set-up-dev-machine"
  register: set_up_dev_machine_repository

- name: Clone set-up-dev-machine repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/set-up-dev-machine.git"
    dest: "{{ personal_github_directory }}/set-up-dev-machine"
  when: set_up_dev_machine_repository.stat.exists == False

- name: Fetch content of set-up-dev-machine remote repository
  shell: cd "{{ personal_github_directory }}/set-up-dev-machine" && git fetch origin
  when: set_up_dev_machine_repository.stat.exists == False

- name: Update Git remote URL of local set-up-dev-machine repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/set-up-dev-machine/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/set-up-dev-machine.git'
    line: '        url = git@github.com:MannyFay/set-up-dev-machine.git'
  when: set_up_dev_machine_repository.stat.exists == False