- name: Checking, if device-recovery-protocol repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/device-recovery-protocol"
  register: device_recovery_protocol_repository

- name: Clone device-recovery-protocol repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/device-recovery-protocol.git"
    dest: "{{ personal_github_directory }}/device-recovery-protocol"
  when: device_recovery_protocol_repository.stat.exists == False

- name: Fetch content of device-recovery-protocol remote repository
  shell: cd "{{ personal_github_directory }}/device-recovery-protocol" && git fetch origin
  when: device_recovery_protocol_repository.stat.exists == False

- name: Update Git remote URL of device-recovery-protocol repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/device-recovery-protocol/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/device-recovery-protocol.git'
    line: '        url = git@github.com:MannyFay/device-recovery-protocol.git'
  when: device_recovery_protocol_repository.stat.exists == False