#------------------------------------------------------------------------------
#----- mannydark.nvim

- name: Checking, if mannydark.nvim repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/mannydark.nvim"
  register: mannydark_nvim_repository

- name: Clone mannydark.nvim repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/mannydark.nvim.git"
    dest: "{{ personal_github_directory }}/mannydark.nvim"
  when: mannydark_nvim_repository.stat.exists == False

- name: Fetch content of mannydark.nvim remote repository
  shell: cd "{{ personal_github_directory }}/mannydark.nvim" && git fetch origin
  when: mannydark_nvim_repository.stat.exists == False

- name: Update Git remote URL of local mannydark.nvim repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/mannydark.nvim/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/mannydark.nvim.git'
    line: '        url = git@github.com:MannyFay/mannydark.nvim.git'
  when: mannydark_nvim_repository.stat.exists == False