- name: Checking, if everest-container repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/contributions/everest-container"
  register: everest_container_repository

- name: Clone everest-container repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/everest-container.git"
    dest: "{{ personal_github_directory }}/contributions/everest-container"
  when: everest_container_repository.stat.exists == False

- name: Fetch content of everest-container remote repository
  shell: cd "{{ personal_github_directory }}/contributions/everest-container" && git fetch origin
  when: everest_container_repository.stat.exists == False

- name: Update Git remote URL of local everest-container repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/contributions/everest-container/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/everest-container.git'
    line: '        url = git@github.com:MannyFay/everest-container.git'
  when: everest_container_repository.stat.exists == False