#------------------------------------------------------------------------------
#----- nvim

- name: Checking, if nvim repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/nvim"
  register: nvim_repository

- name: Clone nvim repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/nvim.git"
    dest: "{{ personal_github_directory }}/nvim"
  when: nvim_repository.stat.exists == False

- name: Fetch content of nvim remote repository
  shell: cd "{{ personal_github_directory }}/nvim" && git fetch origin
  when: nvim_repository.stat.exists == False

- name: Update Git remote URL of local nvim repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/mannydark.nvim/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/nvim.git'
    line: '        url = git@github.com:MannyFay/nvim.git'
  when: nvim_repository.stat.exists == False