- name: Checking, if everest-validation repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/contributions/everest-validation"
  register: everest_validation_repository

- name: Clone everest-validation repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/everest-validation.git"
    dest: "{{ personal_github_directory }}/contributions/everest-validation"
  when: everest_validation_repository.stat.exists == False

- name: Fetch content of everest-validation remote repository
  shell: cd "{{ personal_github_directory }}/contributions/everest-validation" && git fetch origin
  when: everest_validation_repository.stat.exists == False

- name: Update Git remote URL of local everest-validation repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/contributions/everest-validation/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/everest-validation.git'
    line: '        url = git@github.com:MannyFay/everest-validation.git'
  when: everest_validation_repository.stat.exists == False