- name: Checking, if everest-http repository exists already on disk
  stat:
    path: "{{ personal_github_directory }}/contributions/everest-http"
  register: everest_http_repository

- name: Clone everest-http repository if it not exists already on disk
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/everest-http.git"
    dest: "{{ personal_github_directory }}/contributions/everest-http"
  when: everest_http_repository.stat.exists == False

- name: Fetch content of everest-http remote repository
  shell: cd "{{ personal_github_directory }}/contributions/everest-http" && git fetch origin
  when: everest_http_repository.stat.exists == False

- name: Update Git remote URL of local everest-http repository to use SSH
  ansible.builtin.lineinfile:
    path: "{{ personal_github_directory }}/contributions/everest-http/.git/config"
    regexp: '^(\s*)url\s*=\s*https://github.com/MannyFay/everest-http.git'
    line: '        url = git@github.com:MannyFay/everest-http.git'
  when: everest_http_repository.stat.exists == False