---
#- import_tasks: clone-ansible.yml
#- import_tasks: clone-device-recovery-protocol.yml
#- import_tasks: clone-dotfiles.yml
#- import_tasks: clone-mannydark-nvim.yml
#- import_tasks: clone-nvim.yml
#- import_tasks: clone-set-up-dev-machine.yml
#- import_tasks: clone-short-cuts-and-commands.yml
#- import_tasks: clone-everest-app.yml
#- import_tasks: clone-everest-container.yml
#- import_tasks: clone-everest-http.yml
#- import_tasks: clone-everest-validation.yml
#- import_tasks: remove-existing-gitconfig.yml
#- import_tasks: set-global-gitconfig.yml
- import_tasks: clone-repositories.yml
- import_tasks: remove-existing-gitignore.yml
- import_tasks: set-global-gitignore.yml


# After everything, make ansible ssh (if this work while ansible runs?!?)
#- name: Checking, if dotfiles repository exists already on disk
#  stat:
#    path: "{{ personal_github_directory }}/dotfiles"
#  register: dotfiles_repository
#
#- name: Clone dotfiles repository if it not exists already on disk
#  become_user: "{{ username }}"
#  ansible.builtin.git:
#    repo: "https://github.com/MannyFay/dotfiles.git"
#    dest: "{{ personal_github_directory }}/dotfiles"
#  when: dotfiles_repository.stat.exists == False
#
#- name: Fetch content of remote repository
#  shell: cd "{{ personal_github_directory }}/dotfiles" && git fetch
