---
- name: Symlink global Git configuration
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Create symbolic link to own global .gitconfig file in dotfiles repository..."
  block:

    - when: os_type in ["arch", "macos", "ubuntu"]
      name: "{{ task_name }}"
      shell: ln -s "{{ unix_dotfiles_directory }}/git/account-config/global" "{{ unix_home_directory }}/.gitconfig"

    - when: os_type == "windows"
      name: "{{ task_name }}"
      ansible.builtin.shell: mklink "{{ windows_wsl_home_directory }}/.gitconfig" "{{ windows_dotfiles_directory }}/git/account-config/global"
      args:
        creates: "{{ windows_wsl_home_directory }}/.gitconfig"

