- name: Remove .gitignore file from ~/ if it exists already
  become: true
  command: rm -f "{{ lookup('env', 'HOME') }}/.gitignore"
  when: os_type in ["arch", "macos", "ubuntu"]

- name: Link Global Git Ignore File
  become: true
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - ln -s "{{ personal_github_directory }}/dotfiles/git/gitignore" "{{ lookup('env', 'HOME') }}/.gitignore"
  when: os_type in ["arch", "macos", "ubuntu"]