---
- name: Symlink global .gitignore file
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Create symbolic link to own global .gitignore file in dotfiles repository..."
  block:

    - when: os_type in ["arch", "macos", "ubuntu"]
      name: "{{ task_name }}"
      shell: ln -s "{{ unix_personal_github_directory }}/dotfiles/git/gitignore" "{{ lookup('env', 'HOME') }}/.gitignore"

    - when: os_type == "windows"
      name: "{{ task_name }}"
      ansible.builtin.shell: mklink "{{ windows_wsl_home_directory }}/.gitconfig" "{{ windows_dotfiles_directory }}/git/account-config/global"
      args:
        creates: "{{ windows_wsl_home_directory }}/.gitconfig"

