---
- name: Install Microsoft Edge Browser
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Installing Microsoft Edge Browser"
  block:
    - name: "{{ task_name }}"
      when: os_type == "arch"
      ansible.builtin.command:
        cmd: yay -S --noconfirm microsoft-edge-stable-bin
      become: false
      register: edge_install
      changed_when: "'there is nothing to do' not in edge_install.stdout"

    - name: "{{ task_name }}"
      when: os_type == "macos"
      community.general.homebrew_cask:
        name: microsoft-edge
        state: present

    - name: "{{ task_name }}"
      when: os_type == "ubuntu"
      ansible.builtin.apt:
        name: microsoft-edge-stable
        state: present
        update_cache: true

    - name: Notify about Microsoft Edge installation
      when: os_type in ["arch, macos, ubuntu"]
      ansible.builtin.debug:
        msg: "Microsoft Edge browser installation completed."
