---
- name: Download chrome
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Downloading Google Chrome browser..."
  block:

    - when: os_type == "arch"
      name: "{{ task_name }}"
      shell: git clone https://aur.archlinux.org/google-chrome.git

    - when: os_type == "ubuntu"
      name: "{{ task_name }}"
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
