---
- name: Add GPG key of the Docker repository
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Adding GPG key from Docker..."
  block:
    - name: "{{ task_name }}"
      when: os_type == "ubuntu"
      ansible.builtin.command: |
        curl -fsSL \
        https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      state: present

    - name: Notify about adding Docker GPG key
      when: os_type == "ubuntu"
      ansible.builtin.debug:
        msg: "Adding Docker GPG key completed."
