---
- name: Install tmate
  become: true
  vars:
    task_name: "---> Installing tmate instant terminal sharing on device..."
  block:
    - when: os_type == "arch"
      name: "{{ task_name }}"
      shell: pacman -S tmate

    - when: os_type == "macOS"
      name: "{{ task_name }}"
      shell: brew install tmate

    - when: os_type == "ubuntu"
      name: "{{ task_name }}"
      apt:
        name: tmate

    - when: os_type == "windows"
      name: "{{ task_name }}"
      shell: cd "{{ win_wsl_home_dir }}" && sudo apt install tmate