---
- name: Symlink own Alacritty configuration file
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Create symlink to own Alacritty configuration file..."
  block:
    - name: "{{ task_name }}"
      when: os_type in ["arch", "macos", "ubuntu"]
      ansible.builtin.command: |
        ln -s "{{ alacritty_unix_conf_src }}" \
        "{{ alacritty_unix_conf_dest }}"
      state: present

    - name: "{{ task_name }}"
      when: os_type == 'Windows'
      ansible.windows.win_shell: |
        New-Item -ItemType SymbolicLink -Path \
        "{{ alacritty_win_conf_dest }}" -Target \
        "{{ alacritty_win_conf_src }}"
      state: present

    - name: Notify about Alacrity config symlink
      ansible.builtin.debug:
        msg: "Alacritty Configuration Symlink creation completed."
