---
- name: Install Alacritty Terminal Emulator
  become: true
  become_user: "{{ username }}"
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - install-alacritty.yml
    - setup-directory.yml
    - remove-config.yml
    - link-own-config.yml

  block:
    - name: Notify about Alacrity setup
      ansible.builtin.debug:
        msg: "Alacritty setup completed."
