---
- name: Remove .alacritty.toml file from ~/ if it exists already (Unix)
  become: true
  vars:
    task_name: "---> Remove .alacritty.toml file if it exists already..."
  block:
    - name: "{{ task_name }}"
      when: os_type in ["arch", "macos", "ubuntu"]
      ansible.builtin.shell: rm -f "{{ alacritty_unix_conf_dest }}"
      state: present

    - name: "{{ task_name }}"
      when: os_type == 'Windows'
      ansible.windows.win_shell: |
        Remove-Item -Path "{{ alacritty_win_conf_dest }}" \
        -Force -ErrorAction SilentlyContinue
      state: present

    - name: Notify about Alacrity config removement
      ansible.builtin.debug:
        msg: "Alacritty Configuration removement completed."
