---
- name: Checking, if ~/.config/alacritty directory exists already on disk
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/alacritty"
  register: alacritty_directory
  when: os_type in ["arch", "macos", "ubuntu"]

- name: Create Alacritty directory in ~/.config
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    mode: '0755'
  with_items:
    - "{{ lookup('env', 'HOME') }}/.config/alacritty"
  when: alacritty_directory.stat.exists == False and os_type in ["arch", "macos", "ubuntu"]
