---
- name: Checking, if ~/.config/alacritty directory exists already on disk (Unix)
  vars:
    task_name_check_directory: "---> Checking, if Alacritty configuration directory exists already on device..."
    task_name_create_directory: "---> Creating Alacritty configuration directory on device..."
  block:

    - when: os_type in ["arch", "macos", "ubuntu"]
      name: "{{ task_name_check_directory }}"
      stat:
        path: "{{ unix_alacritty_directory_path }}"
      register: alacritty_directory

    - when: os_type == "windows"
      name: "{{ task_name_check_directory }}"
      ansible.windows.win_stat:
        path: "{{ windows_alacritty_directory_path }}"
      register: alacritty_directory



    - when: alacritty_directory.stat.exists == False and os_type in ["arch", "macos", "ubuntu"]
      name: "{{ task_name_create_directory }}"
      ansible.builtin.file:
        path: "{{ unix_alacritty_directory_path }}"
        state: directory
        owner: "{{ username }}"
        mode: '0755'

    - when: not alacritty_directory.stat.exists and os_type == 'Windows'
      name: "{{ task_name_create_directory }}"
      ansible.windows.win_file:
        path: "{{ windows_alacritty_directory_path }}"
        state: directory
        owner: "{{ username }}"
        mode: '0755'
