---
- name: Checking, if Alacritty directory exists. If not, it will be created.
  vars:
    task_name_check_directory: "---> Checking, if Alacritty directory exists..."
    task_name_create_directory: "---> Creating Alacritty directory on device..."
  block:
    - name: "{{ task_name_check_directory }}"
      when: os_type in ["arch", "macos", "ubuntu"]
      ansible.builtin.stat:
        path: "{{ alacritty_unix_dir }}"
      register: alacritty_directory

    - name: "{{ task_name_check_directory }}"
      when: os_type == "windows"
      ansible.windows.win_stat:
        path: "{{ alacritty_win_dir }}"
      register: alacritty_directory

    - name: "{{ task_name_create_directory }}"
      when: >
        not alacritty_directory.stat.exists and
        os_type in ["arch", "macos", "ubuntu"]
      ansible.builtin.file:
        path: "{{ alacritty_unix_dir }}"
        state: directory
        owner: "{{ username }}"
        mode: "0755"

    - name: "{{ task_name_create_directory }}"
      when: >
        not alacritty_directory.stat.exists and
        os_type == 'Windows'
      ansible.windows.win_file:
        path: "{{ alacritty_win_dir }}"
        state: directory
        owner: "{{ username }}"
        mode: "0755"

    - name: Notify about Alacrity directory setup
      ansible.builtin.debug:
        msg: "Alacritty directory setup completed."
