---
- name: Remove nvim directory from ~/.config if it exists already
  become: true
  vars:
    task_name: "---> Removing Neovim configuration directory if it exists already on device..."
  block:

    - when:  os_type in unix_os_types
      name:  "{{ task_name }}"
      shell: rm -rf "{{ unix_nvim_config_directory }}"

    - when:  os_type == "windows"
      name:  "{{ task_name }}"
      shell: rm -rf "{{ windows_nvim_config_directory }}"
