---
- name: Install nerd fonts
  become: true
  become_user: "{{ username }}"
  vars:
    task_name: "---> Installing Meslo Nerd Font..."
  block:

    - when: os_type == "arch"
      name: "{{ task_name }}"
      shell: cp -r "{{ unix_own_meslo_font_directory_path }}/"* "/usr/share/fonts/TTF/"

    - when: os_type == "macos"
      name: "{{ task_name }}"
      ansible.builtin.command: >
        open -b com.apple.FontBook "{{ item }}"
      with_fileglob:
        - "{{ font_package }}"

    - when: os_type == "ubuntu"
      name: "{{ task_name }}"
      shell: fc-cache -fv

    - when: os_type == "windows"
      name: "{{ task_name }}"
      win_shell: |
        $shell = New-Object -ComObject Shell.Application
        $fontFolder = $shell.Namespace(0x14)
        $fontFolder.Items().InvokeVerb("Install")
